#!/bin/sh
#curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
#    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

curl   \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
--output plug.vim

install .vimrc ~/
install -D plug.vim ~/.vim/autoload/plug.vim
rm plug.vim
