#!/bin/sh
#curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
#    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

VIMPLUG=~/.vim/autoload/plug.vim
if [ ! -f  $VIMPLUG ]; then
  curl https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim --output plug.vim

  install -D plug.vim ~/.vim/autoload/plug.vim
  rm plug.vim
fi

install .vimrc ~/
