#!/bin/sh

if [ -f ~/.vimrc ]; then
  if [ `(git diff --staged | wc -l)` -ne 0 ]; then
    echo "Make commit before"
    exit -1
  fi
  cp ~/.vimrc ./
  git add .vimrc
  git commit -m "- update .vimrc"
else
  echo "Not exist .vimrc"
  exit -1
fi
